### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bmarini** [brendon/canonix#9]
Hey Bredon, I was hoping you'd like to add an MIT license to this project. I'm using this project via [ruby-saml](https://github.com/onelogin/ruby-saml) which is MIT licensed. What do you think?

**Comment by brendon** [comment]
Hi Ben, It's probably moot because canonix isn't actually required in the
latest version of ruby-saml. I've submitted a pull request to remove the
dependency but they haven't done it for whatever reason (it's been 5
months). Perhaps you could add your support to that request? The canonix
code isn't used in ruby-saml so you could probably ignore the lack of
licence in this case? I'm actually planning to shut this project down once
they merge that change because there are much better ways to do this now.

Have a great day!

Brendon

**Comment by bmarini** [comment]
Ah I see. Thanks for the explanation!

**Comment by brendon** [comment]
Woah! :) Haha, blast from the past. I know they've merged it now because I upgraded ruby-saml a couple of years ago.
